# Generated by Django 5.0.4 on 2024-05-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ('nome',)},
        ),
    ]
